package ibc

const (
	IbcModule                             = "ibc"
	IbcClientStatesMsgType                = "ibc-client-states"
	IbcClientStateMsgType                 = "ibc-client-state"
	IbcClientStatusMsgType                = "ibc-client-status"
	IbcClientConsensusStatesMsgType       = "ibc-client-consensus-states"
	IbcClientConsensusStateHeightsMsgType = "ibc-client-consensus-state-heights"
	IbcClientConsensusStateMsgType        = "ibc-client-consensus-state"
	IbcClientHeaderMsgType                = "ibc-client-header"
	IbcClientSelfConsensusStateMsgType    = "ibc-client-self-consensus-state"
	IbcClientParamsMsgType                = "ibc-client-params"
	IbcConnectionConnectionsMsgType       = "ibc-connection-connections"
	IbcConnectionConnectionMsgType        = "ibc-connection-connection"
	IbcConnectionClientConnectionsMsgType = "ibc-connection-client-connections"
	IbcChannelChannelsMsgType             = "ibc-channel-channels"
	IbcChannelChannelMsgType              = "ibc-channel-channel"
	IbcChannelConnectionsMsgType          = "ibc-channel-connections"
	IbcChannelClientStateMsgType          = "ibc-channel-client-state"
	IbcChannelPacketCommitmentsMsgType    = "ibc-channel-packet-commitments"
	IbcChannelPacketCommitmentMsgType     = "ibc-channel-packet-commitment"
	IbcChannelPacketReceiptMsgType        = "ibc-channel-packet-receipt"
	IbcChannelPacketAckMsgType            = "ibc-channel-packet-ack"
	IbcChannelUnreceivedPacketsMsgType    = "ibc-channel-unreceived-packets"
	IbcChannelUnreceivedAcksMsgType       = "ibc-channel-unreceived-acks"
	IbcChannelNextSequenceMsgType         = "ibc-channel-next-sequence"
	IbcTransferDenomTracesMsgType         = "ibc-transfer-denom-traces"
	IbcTransferDenomTraceMsgType          = "ibc-transfer-denom-trace"
	IbcTransferDenomHashMsgType           = "ibc-transfer-denom-hash"
	IbcTransferEscrowAddressMsgType       = "ibc-transfer-escrow-address"
	IbcTransferParamsMsgType              = "ibc-transfer-params"
)
